# Generated by Django 2.2.6 on 2019-12-28 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Coupon Name')),
                ('percentage', models.IntegerField(null=True, verbose_name='Percentage')),
                ('status', models.IntegerField(null=True, verbose_name='Status')),
                ('amount', models.IntegerField(null=True, verbose_name='Amount')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name="License's Name")),
                ('description', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('offered_days', models.IntegerField(null=True, verbose_name='Offered Days')),
                ('account_count', models.IntegerField(null=True, verbose_name='Number of IG Accounts')),
                ('package_price', models.IntegerField(null=True, verbose_name='Package Price')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Register Date')),
                ('status', models.IntegerField(null=True, verbose_name='Status')),
                ('main_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='Order ID')),
                ('signature', models.CharField(max_length=400, null=True, verbose_name='signature')),
                ('payment_status', models.IntegerField(null=True, verbose_name='Payment Status')),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated Date')),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Coupon')),
                ('main_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Package')),
            ],
        ),
    ]
