# Generated by Django 2.2.6 on 2019-12-28 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_results', '0004_auto_20190516_0412'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_celery_results.TaskResult')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='isim')),
                ('surname', models.CharField(max_length=200, null=True, verbose_name='soyisim')),
                ('gsm_no', models.IntegerField(null=True, verbose_name='gsm_no')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='email')),
                ('message', models.TextField(max_length=20000, null=True, verbose_name='mesaj')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Register Date')),
                ('main_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
