# Generated by Django 2.2 on 2020-10-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_api_error_instagram_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram_accounts',
            name='current_proxy',
            field=models.CharField(default='188.166.83.102', max_length=200, verbose_name='Proxy IP Adress'),
        ),
    ]
