# Generated by Django 2.2 on 2020-10-04 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_instagram_accounts_current_proxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagram_accounts',
            name='current_proxy',
        ),
        migrations.CreateModel(
            name='SocinstaProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adress', models.CharField(default='188.166.83.102', max_length=200, verbose_name='Proxy IP Adress')),
                ('username', models.CharField(default='wahow', max_length=200, verbose_name='proxy username')),
                ('password', models.CharField(default='i159753', max_length=200, verbose_name='proxy passoword')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='update_time')),
                ('instagram_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.Instagram_Accounts')),
            ],
        ),
    ]
