# Generated by Django 2.2 on 2020-10-04 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20201004_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socinstaproxy',
            name='instagram_account',
        ),
        migrations.AddField(
            model_name='instagram_accounts',
            name='current_proxy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.SocinstaProxy'),
        ),
    ]
