# Generated by Django 2.2 on 2020-10-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_auto_20201004_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram_apı_constants',
            name='android_version',
            field=models.IntegerField(default=24, verbose_name='Android version'),
        ),
    ]
