# Generated by Django 2.2 on 2020-10-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0009_auto_20201004_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socinstaproxy',
            name='location',
            field=models.CharField(max_length=200, null=True, verbose_name='Location'),
        ),
    ]
