# Generated by Django 2.2 on 2020-10-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0010_auto_20201004_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socinstaproxy',
            name='location',
            field=models.CharField(default='Amsterdam', max_length=200, verbose_name='Location'),
        ),
    ]
