# Generated by Django 2.2 on 2020-10-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0012_auto_20201008_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagram_apı_settings',
            name='app_version',
        ),
        migrations.AddField(
            model_name='instagram_api_user_agent',
            name='app_version',
            field=models.CharField(default='76.0.0.15.395', max_length=100, verbose_name='App version'),
        ),
    ]
